INSERT INTO categories (category, username)
VALUES ('Foreign recipes', 'admin'),
       ('Breakfast', 'admin'),
       ('Main Courses', 'admin'),
       ('Starters', 'admin'),
       ('Desserts', 'admin'),
       ('Party food', 'admin');

INSERT INTO recipes (recipe, prep_time, serves, ingredients, steps, username, category_id)
VALUES ('Tortilla de Patatas', 60, 6, '6 eggs, 300gr of potatoes, 1 onion, oil, salt', 'In a pan fry the onion and the potatoes. When ready, mix the eggs in a bowl and add the onion and potatoes discarting the oil in excess. When all is mixed pour again in the hot pan and cook few minutes in low hit. When almost all the egg has set. When ready, use a dish to flip the tortilla and cook few more minutes. Use the dish to take out the tortilla and ENJOY IT!', 'admin', 1),
('Pasta Carbonara', 15, 4, '4 eggs yolks, 320gr spaghetti, 150gr minced bacon, 80gr parmesan cheese, salt, pepper', 'Put water to boil. Meanwhile cook the bacon in a pan. When water boils, add salt and spaghetti and cook for the indicated time. Meanwhile mix the egg and 1 tbsp of parmesan cheese together in a bowl. When pasta is ready, add to the bowl together with the bacon and stir properly. Before serving, spread the remaining chees and pepper.', 'admin', 1),
('Avocado toast', 8, 2, '2 eggs, 2 slices of favorite bread, 1 avocado, salt, pepper, seeds', 'Poach the eggs. Toast the bread. Spread the avocado on the toasts. Add the poached egg. Season with salt, pepper and seeds.', 'admin', 2),
('Basic Muffin', 45, 5, '2 medium eggs, 125ml vegetable oil, 250ml semi-skimmed milk, 250g golden caster sugar, 400g self-raising flour (or same quantity plain flour and 3 tsp baking powder), 1 tsp salt, 100g chocolate chips or dried fruit such as sultanas or dried cherries (optional)', 'Heat oven to 200C-180C fan-gas 6. Line 2 muffin trays with paper muffin cases. In a large bowl beat 2 medium eggs lightly with a handheld electric mixer for 1 min.
Add 125ml vegetable oil and 250ml semi-skimmed milk and beat until just combined then add 250g golden caster sugar and whisk until you have a smooth batter.
Sift in 400g self-raising flour and 1 tsp salt (or 400g plain flour and 3 tsp baking powder if using) then mix until just smooth. Be careful not to over-mix the batter as this will make the muffins tough.
Stir in 100g chocolate chips or dried fruit if using.
Fill muffin cases two-thirds full and bake for 20-25 mins, until risen, firm to the touch and a skewer inserted in the middle comes out clean. If the trays will not fit on 1 shelf, swap the shelves around after 15 mins of cooking.
Leave the muffins in the tin to cool for a few mins and transfer to a wire rack to cool completely.', 'admin', 2),
('Jollof Rice', 50, 4, 'Long-grain parboiled rice, Vegetable oil, Onion, Tomatoes, Red bell pepper, Garlic, Ginger, Thyme, Curry powder, Bay leaves, Chicken broth, Salt, Pepper, Chicken meat, Fresh parsley for garnish (optional).', 'Prepare the rice by rinsing it under cold water until the water runs clear. Drain and set aside. In a large pot or skillet, heat vegetable oil over medium heat. Add chopped onions and sauté until translucent. Add blended or diced tomatoes and red bell pepper. Cook until the mixture thickens and the oil separates. Stir in minced garlic, grated ginger, thyme, curry powder, bay leaves, salt, and pepper. Cook for an additional 2-3 minutes. Add the rinsed rice to the pot and stir until well-coated. Pour in chicken or vegetable broth, bring to a boil, then reduce heat to low, cover, and simmer for 20-25 minutes or until rice is cooked and liquid is absorbed. Optional: Add protein (chicken, shrimp, or fish) during the last 10-15 minutes of cooking. Once rice is cooked, fluff with a fork, remove bay leaves, and garnish with diced green bell pepper and fresh parsley or cilantro. Serve on its own or with your favorite protein. Enjoy!', 'admin', 1),
('Roasted Duck', 140, 6, 'Whole duck (about 4-5 pounds), Salt, Pepper, 1 tablespoon soy sauce (optional), 1 orange (quartered), Fresh herbs (like thyme or rosemary), 1 tablespoon honey, 2 tablespoons soy sauce, 2 tablespoons balsamic vinegar, 1 tablespoon Dijon mustard.', 'Preheat your oven to 375°F (190°C). Remove giblets from the duck and pat it dry. Season inside and out with salt and pepper. Rub the outside with soy sauce if desired. Stuff the cavity with orange quarters and fresh herbs. Truss the duck by tying the legs together. In a small saucepan, combine honey, soy sauce, balsamic vinegar, and Dijon mustard. Heat over low heat until well combined. Place the duck on a rack in a roasting pan, breast side up. Roast in the preheated oven. After 30 minutes, begin basting the duck with the glaze every 15-20 minutes. Continue roasting until golden brown and the internal temperature reaches at least 165°F (74°C). Let the duck rest for 10-15 minutes before carving. Carve and serve with your favorite sides. Drizzle the glaze over the carved duck for added flavor. Enjoy!', 'admin', 3),
('Cantonese rice', 45, 4, '100gr rice, 1 egg, 85gr cubed ham, 100gr peas, 150gr shrimps, salt, oil', 'Boil the rice. Make an omlette. In a pan cook the pease and the shrimps. When ready pour the diced ham and the diced omlette. When the rice is cooked stir in the pan with all other ingredients.', 'admin', 1),
('Cotolette', 120, 4, '500gr scottona fillets, 1 egg, 150 gr bradcrumbs, salt, olive oil', 'Bread the fillets first with the egg and then with the breadcrumbs. Salt all the pieces. When done deep fry in a pan with prehitted oil.', 'admin', '1'),
('Chicken Quesadillas', 50, 8, '300gr cooked and shredded chicken, 200gr shredded cheddar cheese,  150gr shredded Monterey Jack cheese, 80gr diced tomatoes, 20gr chopped fresh cilantro, 100gr diced red onion, 1 teaspoon ground cumin, 1 teaspoon chili powder, Salt and pepper to taste, 8 small flour tortillas, 2 tablespoons vegetable oil', 'In a large bowl, mix together the shredded chicken, cheddar cheese, Monterey Jack cheese, tomatoes, cilantro, red onion, ground cumin, chili powder, salt, and pepper. Place a tortilla on a flat surface and spoon chicken mixture onto one half of the tortilla. Fold the other half of the tortilla over the filling, creating a half-moon shape. Repeat with the remaining tortillas and chicken mixture. Heat 1 tablespoon of vegetable oil in a large skillet over medium heat. Place a couple of quesadillas in the skillet and cook for 2-3 minutes on each side or until the tortillas are golden brown and the cheese is melted. Remove from the skillet and repeat with the remaining quesadillas, adding more oil as needed. Cut each quesadilla into wedges and serve with your favorite salsa, guacamole, or sour cream. Enjoy your delicious chicken quesadillas!', 'admin', '1'),
('Arepas', 35, 4, '250 grams pre-cooked white or yellow cornmeal (masarepa), 350-400 milliliters warm water, 1 teaspoon salt, 15 milliliters vegetable oil (for cooking)', 'Mix the pre-cooked cornmeal (masarepa) with salt in a large bowl. Gradually add warm water, mixing continuously, until you have a soft, smooth dough. Divide the dough into equal portions and shape each portion into a ball. Flatten each ball to form a disk, about 1.5 to 2 centimeters thick. Heat the vegetable oil in a skillet over medium heat. Add the arepas and cook for about 4-5 minutes on each side or until golden brown and a crust forms. You can serve arepas warm and fill them with your favorite ingredients like cheese, ham, avocado, or any other filling of your choice. Enjoy your simple and delicious arepas!', 'admin', 1);